version: 2

linters-settings:
  gci:
    local-prefixes: github.com/meyeringh/cf-switch
  goimports:
    local-prefixes: github.com/meyeringh/cf-switch
  lll:
    line-length: 140
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - gosec
    - misspell

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - gocognit
        - gocyclo

run:
  timeout: 10m
  tests: true
