{{- if and .Values.auth.createSecret .Values.auth.apiToken -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rbac.secretName }}
  labels:
    {{- include "cf-switch.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth
  annotations:
    cf-switch.io/description: "API authentication token for cf-switch service"
    {{- with .Values.auth.secretAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  apiToken: {{ .Values.auth.apiToken }}
{{- end }}
